export const PERSIAN_DIGITS = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹']

export const GENRE_LABELS = {
  Action: 'اکشن',
  Adventure: 'ماجراجویی',
  Animation: 'انیمیشن',
  Children: 'کودک',
  Comedy: 'کمدی',
  Crime: 'جنایی',
  Documentary: 'مستند',
  Drama: 'درام',
  Fantasy: 'فانتزی',
  'Film-Noir': 'نوآر',
  Horror: 'ترسناک',
  Musical: 'موزیکال',
  Mystery: 'معمایی',
  Romance: 'عاشقانه',
  'Sci-Fi': 'علمی‌تخیلی',
  Thriller: 'هیجان‌انگیز',
  War: 'جنگی',
  Western: 'وسترن',
  '(no genres listed)': 'بدون ژانر',
}

export const GENRE_OPTIONS = Object.entries(GENRE_LABELS).reduce((options, entry) => {
  if (entry[0] !== '(no genres listed)') options.push(entry)
  return options
}, [])

export const NAV_ITEMS = [
  { id: 'home', label: 'خانه' },
  { id: 'concierge', label: 'پیشنهاد هوشمند' },
  { id: 'discover', label: 'کشف فیلم' },
  { id: 'recommendations', label: 'ویژهٔ من', auth: true },
  { id: 'ratings', label: 'امتیازهای من', auth: true },
]

export const MOOD_OPTIONS = [
  ['Feel-good', 'حال‌خوب‌کن', '☀️'],
  ['Thrilled', 'پرهیجان', '⚡'],
  ['Thoughtful', 'فکری و عمیق', '◐'],
  ['Escape', 'فرار از روزمرگی', '✦'],
  ['Comfort', 'آرام و صمیمی', '☕'],
  ['Surprise me', 'غافلگیرم کن', '◆'],
]

export const ERA_OPTIONS = [
  ['Any era', 'همهٔ دوره‌ها'],
  ['Classics', 'کلاسیک'],
  ['80s & 90s', 'دههٔ ۸۰ و ۹۰'],
  ['2000s', '۲۰۰۰ تا ۲۰۱۴'],
  ['Modern', 'مدرن'],
]

export const ORIGIN_OPTIONS = [
  ['Any', 'ایران و جهان'],
  ['Iranian', 'فقط ایران'],
  ['International', 'فقط جهان'],
]

export const METHOD_OPTIONS = [
  ['hybrid', 'ترکیبی'],
  ['collaborative', 'هم‌سلیقه‌ها'],
  ['content', 'شباهت محتوایی'],
  ['popular', 'محبوبیت'],
]

export const COPY = {
  app: {
    documentTitle: 'سینمچ | پیشنهاد هوشمند فیلم',
    skipLink: 'رفتن به محتوای اصلی',
    loadingPage: 'در حال آماده‌سازی پرده…',
    welcome: 'خوش آمدی؛ حساب شما آماده است.',
    loggedOut: 'از حساب خارج شدید.',
    ratingSaved: 'امتیاز ثبت شد و پیشنهادهای شما به‌روز شدند.',
    unknownError: 'یک خطای پیش‌بینی‌نشده رخ داد؛ دوباره تلاش کنید.',
  },
  apiErrors: {
    network: 'ارتباط با سرور برقرار نشد. مطمئن شوید FastAPI در حال اجراست.',
    generic: 'در انجام درخواست مشکلی پیش آمد؛ دوباره تلاش کنید.',
  },
  layout: {
    navLabel: 'منوی اصلی',
    brandLabel: 'سینمچ، صفحهٔ اصلی',
    brandStart: 'سین',
    brandEnd: 'مچ',
    tagline: 'انتخاب هوشمند برای شب فیلم',
    welcome: 'خوش آمدی',
    logout: 'خروج از حساب',
    login: 'ورود یا ثبت‌نام',
    catalogBadge: '۸۷ هزار فیلم',
  },
  home: {
    eyebrow: 'پیشنهاد فیلم، دقیقاً برای همین امشب',
    titleStart: 'کمتر بگرد؛',
    titleAccent: 'بهتر تماشا کن.',
    description: 'سینمچ از حال‌وهوای تو و الگوی هزاران امتیاز واقعی کمک می‌گیرد تا انتخاب بعدی‌ات اتفاقی نباشد.',
    primaryAction: 'ساخت پیشنهاد امشب',
    secondaryAction: 'ورود به آرشیو',
    proof: 'بدون حدس تصادفی · توضیح‌پذیر · سریع',
    statsLabel: 'آمار سامانه',
    statMovies: 'فیلم در آرشیو',
    statRatings: 'امتیاز واقعی',
    statUsers: 'عضو سینمچ',
    statPersian: 'فیلم ایرانی منتخب',
    howEyebrow: 'پشت صحنهٔ پیشنهاد',
    howTitle: 'سه قدم تا فیلم درست',
    featureOneTitle: 'حال امشبت را می‌گیریم',
    featureOneText: 'چند پاسخ کوتاه، سلیقهٔ لحظه‌ای تو را به داده‌ای قابل تحلیل تبدیل می‌کند.',
    featureTwoTitle: '۸۷ هزار فیلم را می‌سنجیم',
    featureTwoText: 'ژانر، شباهت و کیفیت جمعی هم‌زمان بررسی می‌شوند؛ نه فقط یک فهرست محبوب.',
    featureThreeTitle: 'دلیل انتخاب را می‌گوییم',
    featureThreeText: 'هر پیشنهاد با درصد هماهنگی و توضیح روشن می‌آید تا تصمیم نهایی با خودت باشد.',
    iranianEyebrow: 'روی پردهٔ ایران',
    iranianTitle: 'چند انتخاب نزدیک‌تر',
    viewAll: 'مشاهدهٔ همه',
  },
  concierge: {
    eyebrow: 'دستیار انتخاب امشب',
    titleStart: 'حال تو،',
    titleAccent: 'فیلم تو.',
    description: 'پنج انتخاب ساده؛ یک فهرست شخصی، قابل توضیح و آمادهٔ تماشا.',
    progress: 'پنج پرده تا پیشنهاد نهایی',
    moodTitle: 'امشب چه حسی می‌خواهی؟',
    moodHint: 'یک گزینه را انتخاب کن',
    genresTitle: 'کدام دنیاها جذبت می‌کنند؟',
    genresHint: 'حداکثر پنج ژانر',
    originTitle: 'از کدام سینما؟',
    eraTitle: 'کدام دوره؟',
    discoveryTitle: 'چقدر اهل کشف هستی؟',
    discoveryHint: 'از انتخاب‌های مطمئن تا تجربه‌های کمتر دیده‌شده',
    popular: 'محبوب و مطمئن',
    discovery: 'کشف تازه',
    submit: 'نمایش انتخاب‌های من',
    submitting: 'در حال چیدن فهرست…',
    reset: 'شروع دوباره',
    modelNote: 'پاسخ‌ها با TF–IDF، شباهت کسینوسی و امتیازهای واقعی MovieLens تحلیل می‌شوند.',
    resultEyebrow: 'فهرست اختصاصی تو',
    resultTitle: 'فیلم‌هایی برای همین حال',
  },
  discover: {
    eyebrow: 'آرشیو سینمچ',
    titleStart: 'هر فیلم،',
    titleAccent: 'یک در تازه.',
    description: 'میان دهه‌ها و ژانرها حرکت کن، فیلم موردنظرت را پیدا کن و جزئیاتش را پیش از تماشا ببین.',
    searchPlaceholder: 'مثلاً Interstellar یا جدایی…',
    searchLabel: 'جست‌وجوی فیلم',
    searchAction: 'جست‌وجو',
    filters: 'فیلترها',
    genreLabel: 'فیلتر ژانر',
    allGenres: 'همهٔ ژانرها',
    iranianOnly: 'فقط سینمای ایران',
    clear: 'پاک‌کردن فیلترها',
    fullCatalog: 'کاتالوگ کامل',
    iranianCatalog: 'کاتالوگ ایران',
    browse: 'مرور فیلم‌ها',
    previous: 'صفحهٔ قبل',
    next: 'صفحهٔ بعد',
    page: (value) => `صفحهٔ ${value}`,
    result: (value) => `نتیجه برای «${value}»`,
  },
  recommendations: {
    eyebrow: (username) => `برای ${username}`,
    titleStart: 'سلیقه‌ای که',
    titleAccent: 'با تو رشد می‌کند.',
    description: 'هر امتیاز، تصویر دقیق‌تری از فیلمی می‌سازد که احتمالاً دوستش خواهی داشت.',
    refresh: 'به‌روزرسانی',
    note: 'مدل ترکیبی رفتار کاربران هم‌سلیقه را با ژانرهای محبوب تو ادغام می‌کند. تا قبل از سه امتیاز، انتخاب‌های مطمئن محبوبیت نمایش داده می‌شوند.',
    listEyebrow: 'مدل پیشنهادی',
    listTitle: 'ویژهٔ تو',
    empty: 'برای ساخت پیشنهاد، چند فیلم را امتیاز بده',
  },
  ratings: {
    eyebrow: 'دفترچهٔ تماشا',
    titleStart: 'رد پای',
    titleAccent: 'سلیقهٔ سینمایی تو.',
    description: 'امتیازها پایهٔ پیشنهاد شخصی‌اند؛ هر انتخاب به مدل کمک می‌کند دقیق‌تر تو را بشناسد.',
    aria: (rating) => `امتیاز ${rating} از ۵`,
    outOf: 'از ۵',
    empty: 'هنوز امتیازی ثبت نکرده‌ای',
    emptyText: 'چند فیلم را پیدا کن و امتیاز بده تا پیشنهادهای شخصی فعال شوند.',
    discoverAction: 'رفتن به آرشیو فیلم‌ها',
  },
  auth: {
    eyebrow: 'حساب شخصی',
    titleStart: 'سلیقه‌ات را نگه دار؛',
    titleAccent: 'انتخاب‌ها را بهتر کن.',
    description: 'فقط سه فیلم را امتیاز بده تا پیشنهاد شخصی بر اساس کاربران هم‌سلیقه فعال شود.',
    loginTab: 'ورود',
    registerTab: 'ساخت حساب',
    username: 'نام کاربری',
    usernamePlaceholder: 'مثلاً filmlover…',
    password: 'رمز عبور',
    passwordPlaceholder: 'حداقل ۶ نویسه…',
    pending: 'کمی صبر کنید…',
    loginAction: 'ورود به سینمچ',
    registerAction: 'ساخت حساب',
    privacy: 'رمز عبور به‌صورت هش‌شده ذخیره می‌شود و متن آن قابل بازیابی نیست.',
    benefitsTitle: 'حساب کاربری چه کمکی می‌کند؟',
    benefits: [
      ['پیشنهاد دقیق‌تر', 'یادگیری از امتیازهای واقعی تو'],
      ['تکرار کمتر', 'کنارگذاشتن فیلم‌هایی که دیده‌ای'],
      ['کنترل بیشتر', 'مقایسهٔ مدل ترکیبی، محتوایی و هم‌سلیقه'],
    ],
  },
  card: {
    details: 'دیدن جزئیات',
    detailsAria: (title) => `مشاهدهٔ جزئیات ${title}`,
    rate: 'امتیاز',
    match: (value) => `${value}٪ هماهنگی`,
  },
  details: {
    back: 'بازگشت به فهرست',
    loadingTitle: 'در حال آماده‌سازی فیلم',
    loading: 'در حال جمع‌آوری اطلاعات فیلم…',
    eyebrow: 'پروندهٔ فیلم',
    matchLabel: 'هماهنگی با انتخاب تو',
    aboutTitle: 'پیش از تماشا بدان',
    experienceTitle: 'فضای فیلم',
    bestForTitle: 'مناسب برای',
    communityTitle: 'نظر جامعهٔ MovieLens',
    rating: 'میانگین امتیاز',
    votes: 'تعداد امتیاز',
    year: 'سال انتشار',
    source: 'منبع اطلاعات',
    noRating: 'بدون امتیاز',
    realData: 'دادهٔ واقعی',
    reasonTitle: 'چرا به تو پیشنهاد شد؟',
    rateAction: 'ثبت امتیاز من',
    similarEyebrow: 'ادامهٔ مسیر',
    similarTitle: 'اگر این فضا را پسندیدی',
    dataTransparency: 'شفافیت داده',
  },
  ratingDialog: {
    title: 'ثبت امتیاز',
    prompt: (title) => `تجربهٔ تماشای «${title}» چطور بود؟`,
    aria: (value) => `${value} از ۵ ستاره`,
    save: 'ثبت امتیاز',
    saving: 'در حال ثبت…',
  },
  common: {
    emptyTitle: 'چیزی پیدا نشد',
    emptyText: 'فیلترها را تغییر بده و دوباره امتحان کن.',
    close: 'بستن',
  },
}
