export const PERSIAN_DIGITS = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹']

export const GENRE_LABELS = {
  Action: 'اکشن',
  Adventure: 'ماجراجویی',
  Animation: 'انیمیشن',
  Children: 'کودک',
  Comedy: 'کمدی',
  Crime: 'جنایی',
  Documentary: 'مستند',
  Drama: 'درام',
  Fantasy: 'فانتزی',
  'Film-Noir': 'نوآر',
  Horror: 'ترسناک',
  Musical: 'موزیکال',
  Mystery: 'معمایی',
  Romance: 'عاشقانه',
  'Sci-Fi': 'علمی‌تخیلی',
  Thriller: 'هیجان‌انگیز',
  War: 'جنگی',
  Western: 'وسترن',
  '(no genres listed)': 'بدون ژانر',
}

export const GENRE_OPTIONS = Object.entries(GENRE_LABELS).reduce((options, entry) => {
  if (entry[0] !== '(no genres listed)') options.push(entry)
  return options
}, [])

export const NAV_ITEMS = [
  { id: 'home', label: 'خانه' },
  { id: 'concierge', label: 'پیشنهاد هوشمند' },
  { id: 'discover', label: 'کشف آثار' },
  { id: 'recommendations', label: 'ویژهٔ من', auth: true },
  { id: 'tracker', label: 'دفتر تماشا', auth: true },
]

export const MOOD_OPTIONS = [
  ['feel_good', 'حال‌خوب‌کن'],
  ['need_laugh', 'نیاز به خنده'],
  ['low_energy', 'کم‌انرژی'],
  ['thrill', 'پرهیجان'],
  ['thoughtful', 'فکری'],
  ['emotional', 'احساسی'],
  ['cozy', 'آرام و صمیمی'],
  ['romantic', 'عاشقانه'],
  ['inspired', 'الهام‌بخش'],
  ['nostalgic', 'نوستالژیک'],
  ['escape', 'فرار از روزمرگی'],
  ['surprise', 'غافلگیرم کن'],
]

export const ERA_OPTIONS = [
  ['Any era', 'همهٔ دوره‌ها'],
  ['Classics', 'کلاسیک'],
  ['80s & 90s', 'دههٔ ۸۰ و ۹۰'],
  ['2000s', '۲۰۰۰ تا ۲۰۱۴'],
  ['Modern', 'مدرن'],
]

export const ORIGIN_OPTIONS = [
  ['Any', 'ایران و جهان'],
  ['Iranian', 'فقط ایران'],
  ['International', 'فقط جهان'],
]

export const MODE_OPTIONS = [
  ['balanced', 'متعادل'],
  ['familiar', 'آشنا و مطمئن'],
  ['explore', 'کشف تازه'],
]

export const COPY = {
  app: {
    documentTitle: 'سینمچ | پیشنهاد و پیگیری فیلم و سریال',
    skipLink: 'رفتن به محتوای اصلی',
    loadingPage: 'در حال آماده‌سازی پرده…',
    welcome: 'خوش آمدی؛ حساب شما آماده است.',
    loggedOut: 'از حساب خارج شدید.',
    ratingSaved: 'امتیاز ثبت شد و پیشنهادهای شما به‌روز شدند.',
    watchlistSaved: 'به واچ‌لیست اضافه شد.',
    watchedSaved: 'در فهرست دیده‌شده‌ها ثبت شد.',
    unknownError: 'یک خطای پیش‌بینی‌نشده رخ داد؛ دوباره تلاش کنید.',
  },
  apiErrors: {
    network: 'ارتباط با سرور برقرار نشد. مطمئن شوید FastAPI در حال اجراست.',
    generic: 'در انجام درخواست مشکلی پیش آمد؛ دوباره تلاش کنید.',
  },
  layout: {
    navLabel: 'منوی اصلی',
    brandLabel: 'سینمچ، صفحهٔ اصلی',
    brandStart: 'سین',
    brandEnd: 'مچ',
    tagline: 'انتخاب و پیگیری فیلم و سریال',
    welcome: 'خوش آمدی',
    logout: 'خروج از حساب',
    account: 'حساب و دفتر تماشا',
    login: 'ورود یا ثبت‌نام',
    footerEyebrow: 'پایان این پرده، آغاز انتخاب بعدی',
    footerTitle: 'برای شب بعدی آماده‌ای؟',
    footerText: 'سینمچ انتخاب فیلم را کوتاه‌تر، شخصی‌تر و توضیح‌پذیر می‌کند؛ تا وقتت صرف تماشا شود، نه جست‌وجو.',
    footerData: 'این محصول از API تی‌ام‌دی‌بی استفاده می‌کند اما مورد تأیید یا گواهی TMDB نیست. امتیازها از MovieLens هستند.',
    footerNavLabel: 'پیوندهای فوتر',
  },
  home: {
    eyebrow: 'پیشنهاد فیلم، دقیقاً برای همین امشب',
    titleStart: 'کمتر بگرد؛',
    titleAccent: 'بهتر تماشا کن.',
    description: 'سینمچ از حال‌وهوای تو و الگوی هزاران امتیاز واقعی کمک می‌گیرد تا فیلم یا سریال بعدی‌ات اتفاقی نباشد.',
    primaryAction: 'ساخت پیشنهاد امشب',
    secondaryAction: 'ورود به آرشیو',
    proof: 'بدون حدس تصادفی · توضیح‌پذیر · سریع',
    statsLabel: 'آمار سامانه',
    statMovies: 'فیلم در آرشیو',
    statSerials: 'سریال در آرشیو',
    statRatings: 'امتیاز واقعی',
    statUsers: 'عضو سینمچ',
    statPersian: 'فیلم ایرانی منتخب',
    howEyebrow: 'پشت صحنهٔ پیشنهاد',
    howTitle: 'سه قدم تا فیلم درست',
    featureOneTitle: 'حال امشبت را می‌گیریم',
    featureOneText: 'چند پاسخ کوتاه، سلیقهٔ لحظه‌ای تو را به داده‌ای قابل تحلیل تبدیل می‌کند.',
    featureTwoTitle: 'هزاران اثر را می‌سنجیم',
    featureTwoText: 'ژانر، شباهت و کیفیت جمعی هم‌زمان بررسی می‌شوند؛ نه فقط یک فهرست محبوب.',
    featureThreeTitle: 'دلیل انتخاب را می‌گوییم',
    featureThreeText: 'هر پیشنهاد با درصد هماهنگی و توضیح روشن می‌آید تا تصمیم نهایی با خودت باشد.',
    iranianEyebrow: 'روی پردهٔ ایران',
    iranianTitle: 'چند انتخاب نزدیک‌تر',
    viewAll: 'مشاهدهٔ همه',
  },
  concierge: {
    eyebrow: 'دستیار انتخاب امشب',
    titleStart: 'حال تو،',
    titleAccent: 'فیلم تو.',
    description: 'حس اصلی و یک حس مکمل را انتخاب کن؛ فهرستی شخصی، متنوع و آمادهٔ تماشا تحویل بگیر.',
    progress: 'پنج انتخاب کوتاه تا فهرست امشب',
    summaryTitle: 'انتخاب‌های امشب',
    summaryHint: 'این خلاصه هم‌زمان با انتخاب‌های تو به‌روز می‌شود.',
    summaryMood: 'حال‌وهوا',
    summaryGenres: 'ژانرها',
    summaryOrigin: 'مبدأ سینما',
    summaryEra: 'دورهٔ زمانی',
    summaryDiscovery: 'میزان کشف',
    noGenres: 'آزاد؛ بدون محدودیت ژانر',
    discoveryValue: (value) => `${value}٪ ماجراجویی`,
    moodTitle: 'امشب چه حسی می‌خواهی؟',
    moodHint: 'یک حس اصلی و در صورت نیاز یک حس مکمل؛ غافلگیرم کن مستقل است',
    genresTitle: 'کدام دنیاها جذبت می‌کنند؟',
    genresHint: 'حداکثر پنج ژانر',
    originTitle: 'از کدام سینما؟',
    eraTitle: 'کدام دوره؟',
    discoveryTitle: 'چقدر اهل کشف هستی؟',
    discoveryHint: 'از انتخاب‌های مطمئن تا تجربه‌های کمتر دیده‌شده',
    popular: 'محبوب و مطمئن',
    discovery: 'کشف تازه',
    submit: 'نمایش انتخاب‌های من',
    submitting: 'در حال چیدن فهرست…',
    reset: 'شروع دوباره',
    modelNote: 'حال‌وهوا، محتوای فیلم، الگوی کاربران هم‌سلیقه و تنوع فهرست با هم سنجیده می‌شوند.',
    resultEyebrow: 'فهرست اختصاصی تو',
    resultMovieTitle: 'فیلم‌هایی برای همین حال',
    resultSerialTitle: 'سریال‌هایی برای همین حال',
    mediaType: 'دنبال چه چیزی هستی؟',
    movie: 'یک فیلم',
    serial: 'یک سریال',
    summaryMedia: 'نوع پیشنهاد',
  },
  discover: {
    eyebrow: 'آرشیو سینمچ',
    titleStart: 'هر فیلم،',
    titleAccent: 'یک در تازه.',
    description: 'میان دهه‌ها و ژانرها حرکت کن، فیلم موردنظرت را پیدا کن و جزئیاتش را پیش از تماشا ببین.',
    searchPlaceholder: 'مثلاً Interstellar یا جدایی…',
    searchLabel: 'جست‌وجوی فیلم',
    searchAction: 'جست‌وجو',
    filters: 'فیلترها',
    genreLabel: 'فیلتر ژانر',
    allGenres: 'همهٔ ژانرها',
    iranianOnly: 'فقط سینمای ایران',
    clear: 'پاک‌کردن فیلترها',
    clearSearch: 'پاک‌کردن جست‌وجو',
    fullCatalog: 'کاتالوگ کامل',
    iranianCatalog: 'کاتالوگ ایران',
    browse: 'مرور فیلم‌ها',
    previous: 'صفحهٔ قبل',
    next: 'صفحهٔ بعد',
    page: (value) => `صفحهٔ ${value}`,
    result: (value) => `نتیجه برای «${value}»`,
    moviesTab: 'فیلم‌ها',
    serialsTab: 'سریال‌ها',
  },
  recommendations: {
    eyebrow: (username) => `برای ${username}`,
    titleStart: 'سلیقه‌ای که',
    titleAccent: 'با تو رشد می‌کند.',
    description: 'هر امتیاز و هر تماشا، تصویر دقیق‌تری از اثری می‌سازد که احتمالاً دوستش خواهی داشت.',
    refresh: 'به‌روزرسانی',
    note: 'متعادل بین سلیقه و تنوع حرکت می‌کند؛ آشنا و مطمئن به انتخاب‌های نزدیک‌تر وزن می‌دهد و کشف تازه تکرار ژانر و دوره را کمتر می‌کند.',
    listEyebrow: 'حالت پیشنهاد',
    listTitle: 'ویژهٔ تو',
    empty: 'برای ساخت پیشنهاد، چند فیلم را امتیاز بده',
    moviesTab: 'پیشنهاد فیلم',
    serialsTab: 'پیشنهاد سریال',
  },
  ratings: {
    eyebrow: 'دفترچهٔ تماشا',
    titleStart: 'رد پای',
    titleAccent: 'سلیقهٔ سینمایی تو.',
    description: 'امتیازها پایهٔ پیشنهاد شخصی‌اند؛ هر انتخاب به مدل کمک می‌کند دقیق‌تر تو را بشناسد.',
    aria: (rating) => `امتیاز ${rating} از ۵`,
    outOf: 'از ۵',
    empty: 'هنوز امتیازی ثبت نکرده‌ای',
    emptyText: 'چند فیلم را پیدا کن و امتیاز بده تا پیشنهادهای شخصی فعال شوند.',
    discoverAction: 'رفتن به آرشیو فیلم‌ها',
  },
  auth: {
    eyebrow: 'حساب شخصی',
    titleStart: 'سلیقه‌ات را نگه دار؛',
    titleAccent: 'انتخاب‌ها را بهتر کن.',
    description: 'فقط سه فیلم را امتیاز بده تا پیشنهاد شخصی بر اساس کاربران هم‌سلیقه فعال شود.',
    loginTab: 'ورود',
    registerTab: 'ساخت حساب',
    username: 'نام کاربری',
    usernamePlaceholder: 'مثلاً filmlover…',
    password: 'رمز عبور',
    passwordPlaceholder: 'حداقل ۶ نویسه…',
    pending: 'کمی صبر کنید…',
    loginAction: 'ورود به سینمچ',
    registerAction: 'ساخت حساب',
    privacy: 'رمز به‌صورت هش‌شده و نشست در cookie امن HttpOnly نگه‌داری می‌شود.',
    benefitsTitle: 'حساب کاربری چه کمکی می‌کند؟',
    benefits: [
      ['پیشنهاد دقیق‌تر', 'یادگیری از امتیازهای واقعی تو'],
      ['تکرار کمتر', 'کنارگذاشتن فیلم‌هایی که دیده‌ای'],
      ['کنترل بیشتر', 'انتخاب میان پیشنهاد متعادل، مطمئن یا اکتشافی'],
    ],
  },
  card: {
    details: 'دیدن جزئیات',
    detailsAria: (title) => `مشاهدهٔ جزئیات ${title}`,
    rate: 'امتیاز',
    match: (value) => `${value}٪ هماهنگی`,
    noOverview: 'خلاصهٔ معتبر این اثر هنوز به کاتالوگ افزوده نشده است.',
    watchlist: 'واچ‌لیست',
    watched: 'دیده‌ام',
    trackSerial: 'شروع پیگیری',
    movie: 'فیلم',
    serial: 'سریال',
  },
  onboarding: {
    eyebrow: 'شروع شخصی‌سازی',
    titleStart: 'سه نشانه برای',
    titleAccent: 'شناخت سلیقهٔ تو.',
    description: 'از میان این دوازده فیلم متنوع، دقیقاً سه مورد را امتیاز بده؛ یا فعلاً از این مرحله عبور کن.',
    progress: (value) => `${value} از ۳ فیلم انتخاب شده`,
    rateAria: (title) => `امتیازدهی به ${title}`,
    picked: (value) => `امتیاز ${value} ثبت می‌شود`,
    saving: 'در حال ساخت نمایه…',
    continue: 'ذخیره و ادامه',
    skip: 'فعلاً رد می‌کنم',
  },
  pwa: {
    offline: 'آفلاین هستید؛ پوسته و فیلم‌های عمومی اخیر در دسترس‌اند.',
    update: 'نسخهٔ تازهٔ سینمچ آماده است.',
    updateAction: 'به‌روزرسانی',
    install: 'نصب سینمچ',
    ios: 'برای نصب در iOS، Share و سپس Add to Home Screen را بزنید.',
  },
  details: {
    back: 'بازگشت به فهرست',
    loadingTitle: 'در حال آماده‌سازی فیلم',
    loading: 'در حال جمع‌آوری اطلاعات فیلم…',
    eyebrow: 'پروندهٔ فیلم',
    matchLabel: 'هماهنگی با انتخاب تو',
    aboutTitle: 'پیش از تماشا بدان',
    experienceTitle: 'فضای فیلم',
    bestForTitle: 'مناسب برای',
    communityTitle: 'نظر جامعهٔ MovieLens',
    rating: 'میانگین امتیاز',
    votes: 'تعداد امتیاز',
    year: 'سال انتشار',
    source: 'منبع اطلاعات',
    noRating: 'بدون امتیاز',
    realData: 'دادهٔ واقعی',
    reasonTitle: 'چرا به تو پیشنهاد شد؟',
    rateAction: 'ثبت امتیاز من',
    similarEyebrow: 'ادامهٔ مسیر',
    similarTitle: 'اگر این فضا را پسندیدی',
    dataTransparency: 'شفافیت داده',
    addWatchlist: 'افزودن به واچ‌لیست',
    markWatched: 'ثبت به‌عنوان دیده‌شده',
    trackSerial: 'پیگیری این سریال',
    mediaType: 'نوع اثر',
  },
  ratingDialog: {
    title: 'ثبت امتیاز',
    prompt: (title) => `تجربهٔ تماشای «${title}» چطور بود؟`,
    aria: (value) => `${value} از ۵ ستاره`,
    save: 'ثبت امتیاز',
    saving: 'در حال ثبت…',
  },
  tracker: {
    eyebrow: (username) => `دفتر تماشای ${username}`,
    titleStart: 'هر تماشا،',
    titleAccent: 'یک خانهٔ روشن.',
    description: 'فیلم‌ها، واچ‌لیست و پیشرفت سریال‌ها را یک‌جا نگه دار و ریتم تماشایت را در طول سال ببین.',
    activityTitle: 'فعالیت تماشای یک سال اخیر',
    activityHint: 'هر خانه یک روز است؛ رنگ پرتر یعنی فیلم یا قسمت‌های بیشتری دیده‌ای.',
    activityScrollLabel: 'نمودار فعالیت تماشا؛ برای دیدن روزهای بیشتر افقی پیمایش کنید',
    totalUnits: 'فیلم و قسمت دیده‌شده',
    activeDays: 'روز فعال',
    currentStreak: 'روز پیوستهٔ فعلی',
    longestStreak: 'بیشترین روز پیوسته',
    less: 'کمتر',
    more: 'بیشتر',
    watchlist: 'واچ‌لیست',
    watching: 'در حال تماشا',
    completed: 'دیده‌شده‌ها',
    emptyWatchlist: 'واچ‌لیست هنوز خالی است',
    emptyWatching: 'هنوز سریالی را در حال تماشا ثبت نکرده‌ای',
    emptyCompleted: 'هنوز تماشایی ثبت نشده است',
    findTitles: 'پیدا کردن فیلم و سریال',
    ratingsAction: 'دیدن امتیازهای من',
    updateProgress: 'ثبت پیشرفت',
    remove: 'حذف از دفتر',
    removeTitle: 'حذف از دفتر تماشا',
    removePrompt: (title) => `«${title}» از دفتر تماشا حذف شود؟`,
    removeHint: 'سابقهٔ فعالیت‌های ثبت‌شده پاک نمی‌شود.',
    removeConfirm: 'حذف عنوان',
    removing: 'در حال حذف…',
    progressTitle: 'پیشرفت سریال',
    season: 'فصل فعلی',
    episode: 'قسمت فعلی',
    watchedEpisodes: 'تعداد کل قسمت‌های دیده‌شده',
    saveProgress: 'ذخیرهٔ پیشرفت',
    saving: 'در حال ذخیره…',
    remaining: (value) => `${value} قسمت باقی مانده`,
    unknownRemaining: 'تعداد قسمت‌های باقی‌مانده نامشخص است',
    progress: (value) => `${value}٪ پیشرفت`,
    activityLabel: (date, count) => `${date}: ${count} تماشا`,
  },
  common: {
    emptyTitle: 'چیزی پیدا نشد',
    emptyText: 'فیلترها را تغییر بده و دوباره امتحان کن.',
    close: 'بستن',
    cancel: 'انصراف',
  },
}
